name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: BoardGame
        path: target/*.jar

    - name: Trivy FS Scan
      run: |
        trivy fs --format table -o trivy-fs-report.html .

    - name: Analyze with SonarQube
      uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}   
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }} 
      with:
        args:
          -Dsonar.projectKey=BoardGame
          -Dsonar.java.binaries=.
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build Docker Image
      run: |
          docker build -t javaexpress/boardgame:latest .        

    - name: Trivy Image Scan
      run: |
          trivy image --format table -o trivy-image-report.html javaexpress/boardgame:latest 

    - name: Push Docker Image
      run: |
          docker push javaexpress/boardgame:latest

    - name: Deploy to Kubernetes
      run: |
          kubectl apply -f deployment-service.yaml      
          kubectl get pods
          kubectl get svc
    
    - name: Clean the workspace
      uses: docker://alpine
      with:
        args: /bin/sh -c "find \"${GITHUB_WORKSPACE}\" -mindepth 1 ! -name . -prune -exec rm -rf {} +"            
